/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Objects;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    FileReader jsonFileReader = ReadJsonFile("recentquotes.json"); // Read the File
    quotesAndAuthor[] quotesAndAuthorsArray = ArrayOfquotesAndAuthor(jsonFileReader);
    @Test void TestReadAuthor(){
        assertEquals("Marilyn Monroe", quotesAndAuthorsArray[0].getAuthor());
    }
    @Test void TestReadText(){
        assertEquals("I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.", quotesAndAuthorsArray[0].getText());
    }
    @Test void TestArgAuthor(){
        String[] args ={"author","Marilyn"};
        assertTrue(quotesAndAuthorsArray[0].getAuthor().contains(args[1]));
    }
    @Test void TestArgContains(){
        String[] args ={"contains","angel"};
        assertTrue(quotesAndAuthorsArray[0].getText().contains(args[1]));
    }
    public static FileReader ReadJsonFile(String filename) {
        FileReader filereader = null;
        try {
            // Read From Resource Folder
            String filenameResource = Objects.requireNonNull(Thread.currentThread().getContextClassLoader()
                    .getResource(filename)).getFile();
            filereader = new FileReader(filenameResource);

        } catch (IOException exception) {
            exception.printStackTrace();
        }
        return filereader;
    }

    // Read https://buildcoding.com/parse-json-file-with-gson-library-in-java/
    public static  quotesAndAuthor[] ArrayOfquotesAndAuthor(FileReader jsonFileReader){
        Gson gson = new Gson();
        quotesAndAuthor[] quotesAndAuthorsArray = gson.fromJson(jsonFileReader, quotesAndAuthor[].class);
        return quotesAndAuthorsArray;
    }

}
